name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6.11
        php_version: 8.0
        php_extensions: "sqlite3 xml gd mbstring zip xdebug"
        configuration: phpunit.xml
        coverage_cobertura: coverage/cobertura.xml

    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
          php_version: 8.0
          standard: phpcs.xml
