name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6.11
        php_version: 8.2.10
        php_extensions: "sqlite3 xml gd mbstring zip"
        #bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        args: --coverage-text
        coverage_clover: "coverage/clover.xml"
